paths:
  root: /Users/jpmcdonald/Code/vn2
  raw: /Users/jpmcdonald/Code/vn2/data/raw
  interim: /Users/jpmcdonald/Code/vn2/data/interim
  processed: /Users/jpmcdonald/Code/vn2/data/processed
  submissions: /Users/jpmcdonald/Code/vn2/data/submissions
  scratch: /Users/jpmcdonald/Code/vn2/scratch
  reports: /Users/jpmcdonald/Code/vn2/reports

simulation:
  lead_weeks: 2
  review_weeks: 1
  costs:
    holding: 0.2
    shortage: 1.0

policy_defaults:
  service_level: 0.8333

sip:
  quantiles: [0.01, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95, 0.99]
  horizon_weeks: 8
  conformal_alpha: 0.1           # 90% coverage target
  transform: auto_surd           # sqrt/cbrt/identity via CV scan

mc_opt:
  n_sims: 1000                   # Monte Carlo samples per SKU
  candidate_strategy: base_stock_span
  grid_span: 2.0                 # +/- span in std devs
  max_grid: 400                  # safety cap on order qty
  seed: 17

